/// Medical specializations offered in the doctor-registration picker (ID-4).
/// Covers NMC broad + super specialties, AYUSH streams, and dentistry —
/// searchable in the UI; free text stays allowed so an unlisted
/// sub-specialty never blocks adding a doctor.
const List<String> kMedicalSpecialties = [
  'General Physician (General Medicine)',
  'Family Medicine',
  'Paediatrics',
  'Neonatology',
  'Obstetrics & Gynaecology',
  'Cardiology',
  'Cardiothoracic Surgery',
  'Pulmonology',
  'Neurology',
  'Neurosurgery',
  'Nephrology',
  'Urology',
  'Gastroenterology',
  'Surgical Gastroenterology',
  'Hepatology',
  'Endocrinology',
  'Diabetology',
  'Rheumatology',
  'Medical Oncology',
  'Surgical Oncology',
  'Radiation Oncology',
  'Haematology',
  'Dermatology',
  'Psychiatry',
  'Ophthalmology',
  'ENT (Otorhinolaryngology)',
  'Orthopaedics',
  'General Surgery',
  'Plastic Surgery',
  'Vascular Surgery',
  'Paediatric Surgery',
  'Anaesthesiology',
  'Radiology',
  'Pathology',
  'Microbiology',
  'Emergency Medicine',
  'Critical Care Medicine',
  'Community Medicine',
  'Geriatric Medicine',
  'Sports Medicine',
  'Palliative Medicine',
  'Infectious Diseases',
  'Dentistry',
  'Ayurveda',
  'Homeopathy',
  'Unani',
  'Siddha',
  'Yoga & Naturopathy',
  'Other',
];
