-- CareBridge — Phase 7: one-touch AI summary (Section 8).
--
-- Two layers, and the DB draws the line between them:
--   Layer 1 (safety banner) is DETERMINISTIC — allergies / chronic conditions /
--     current medications straight from the patients row. Never AI-generated.
--   Layer 2 (narrative) is generated by the ai-summary Edge Function calling the
--     Claude API server-side. Its input is assembled HERE, by
--     carebridge_ai_summary_input(), so the "structured fields only" rule is
--     enforced at the database: visit free-text NOTES are deliberately excluded,
--     as are file-based reports (only structured_values from test_reports pass).
--
-- Access model: the input function authorizes off the caller's scoped JWT via
-- current_scope_can_view_patient() — doctor-scoped needs their own grant,
-- admin-scoped inherits via AC-8. Patients and diagnostic partners get nothing.
-- Every call is written to access_logs (Section 10 auditability).
--
-- Caching: ai_summaries stores the latest generated narrative per patient,
-- keyed by a fingerprint of the input. The Edge Function regenerates only when
-- the fingerprint changes — which happens exactly when a new visit or test
-- report lands (Section 8 "regenerate automatically"). Writes are SERVICE-ROLE
-- ONLY (no insert/update policy for authenticated), so a client can never
-- plant a fake "AI" narrative.

-- ============================================================
-- ai_summaries — server-written cache of the layer-2 narrative.
-- ============================================================
create table if not exists ai_summaries (
  patient_id        uuid primary key references patients(id) on delete cascade,
  summary           jsonb not null,          -- {summary, sentence_sources[]}
  model             text,                    -- which Claude model produced it
  input_fingerprint text not null,           -- hash of the structured input
  generated_at      timestamptz not null default now()
);

alter table ai_summaries enable row level security;
grant select on ai_summaries to authenticated;

-- Readable by any clinic scope that may view the patient (doctor grant, or
-- admin via AC-8). No write policies: only the service role (Edge Function)
-- inserts/updates rows.
drop policy if exists ai_summaries_select_scoped on ai_summaries;
create policy ai_summaries_select_scoped on ai_summaries
  for select to authenticated
  using (public.current_scope_can_view_patient(patient_id));

-- ============================================================
-- carebridge_ai_summary_input — the ONLY structured input the AI may see.
-- ============================================================
-- Returns:
--   {
--     "patient_id":  uuid,
--     "banner":      {allergies[], chronic_conditions[], current_medications[]},
--     "visits":      [{visit_id, date, diagnosis, prescriptions[], follow_up_date,
--                      follow_up_completed}],       -- NO free-text notes, ever
--     "tests":       [{test_order_id, test_name, test_type, status, reported_at,
--                      structured_values}]          -- structured results only
--   }
-- Raises if the calling scope may not view the patient.
create or replace function carebridge_ai_summary_input(p_patient uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role   text := current_active_role();
  v_banner jsonb;
  v_visits jsonb;
  v_tests  jsonb;
begin
  -- Clinic scopes only (Section 8: doctor- and admin-scoped sessions), and the
  -- Section 7 access-grant check must pass (AC-8 covers the admin case).
  if v_role not in ('doctor', 'admin') then
    raise exception 'AI summary is only available to a clinic session';
  end if;
  if not public.current_scope_can_view_patient(p_patient) then
    raise exception 'no active grant to view this patient';
  end if;

  -- Layer 1 banner — deterministic, straight from structured fields.
  select jsonb_build_object(
           'allergies',           to_jsonb(p.allergies),
           'chronic_conditions',  to_jsonb(p.chronic_conditions),
           'current_medications', to_jsonb(p.current_medications))
    into v_banner
    from patients p where p.id = p_patient;
  if v_banner is null then
    raise exception 'unknown patient';
  end if;

  -- Visits: structured fields ONLY — diagnosis + structured prescriptions.
  -- v.notes is EXCLUDED by design (Section 8: never raw free-text).
  select coalesce(jsonb_agg(jsonb_build_object(
           'visit_id',            v.id,
           'date',                to_char(v.visit_date, 'YYYY-MM-DD'),
           'diagnosis',           v.diagnosis,
           'follow_up_date',      to_char(v.follow_up_date, 'YYYY-MM-DD'),
           'follow_up_completed', v.follow_up_completed,
           'prescriptions',       coalesce((
             select jsonb_agg(jsonb_build_object(
                      'drug',          rx.drug_name,
                      'dosage',        rx.dosage,
                      'schedule',      rx.schedule,
                      'duration_days', rx.duration_days))
             from prescriptions rx where rx.visit_id = v.id), '[]'::jsonb)
         ) order by v.visit_date), '[]'::jsonb)
    into v_visits
    from visits v where v.patient_id = p_patient;

  -- Tests: only reports with STRUCTURED values; pdf/image files never reach
  -- the model (no OCR, no unparsed scans — Section 8).
  select coalesce(jsonb_agg(jsonb_build_object(
           'test_order_id',     o.id,
           'test_name',         o.test_name,
           'test_type',         o.test_type,
           'status',            o.status,
           'reported_at',       to_char(r.uploaded_at, 'YYYY-MM-DD'),
           'structured_values', r.structured_values
         ) order by o.created_at), '[]'::jsonb)
    into v_tests
    from test_orders o
    left join test_reports r
      on r.test_order_id = o.id and r.report_type = 'structured'
    where o.patient_id = p_patient and o.status <> 'cancelled';

  -- Section 10: every summary view lands in the patient's audit trail,
  -- distinguishing doctor vs clinic_admin (mirrors carebridge_log_view).
  if v_role = 'doctor' and current_active_doctor_id() is not null then
    insert into access_logs (patient_id, accessed_by_type, accessed_by_id, what_viewed)
      values (p_patient, 'doctor', current_active_doctor_id(), 'AI summary');
  elsif v_role = 'admin' and current_clinic_id() is not null then
    insert into access_logs (patient_id, accessed_by_type, accessed_by_id, what_viewed)
      values (p_patient, 'clinic_admin', current_clinic_id(), 'AI summary');
  else
    raise exception 'no scoped identity to log';
  end if;

  return jsonb_build_object(
    'patient_id', p_patient,
    'banner',     v_banner,
    'visits',     v_visits,
    'tests',      v_tests);
end;
$$;

grant execute on function carebridge_ai_summary_input(uuid) to authenticated;
